const  types = {
    ADD_GIF: 'ADD_GIF',
    ADD_GIF_ERROR: 'ADD_GIF_ERROR',
    REMOVE_GIF: 'REMOVE_GIF',
    REMOVE_GIF_ERROR: 'REMOVE_GIF_ERROR',
    SEARCH_GIFS: 'SEARCH_GIFS',
    SEARCH_GIFS_ERROR: 'SEARCH_GIFS_ERROR',
    LOAD_GIFS: 'LOAD_GIFS',
    LOADING_GIFS: 'LOADING_GIFS',
    LOAD_GIFS_ERROR: 'LOAD_GIFS_ERROR'
}

export default types;
